spring:
  kafka:
    security:
      protocol: SASL_SSL

    ssl:
      trust-store-location: classpath:certs/client-truststore.jks
      trust-store-password: changeit

    properties:
      "[sasl.jaas.config]": org.apache.kafka.common.security.scram.ScramLoginModule required username="kafka" password="kafka-secret";
      "[sasl.mechanism]": SCRAM-SHA-512
      "[default.api.timeout.ms]": 20000
      "[request.timeout.ms]": 20000

      "[schema.registry.url]": https://schema-registry1:8081,https://schema-registry2:8081
      "[basic.auth.credentials.source]": USER_INFO
      "[schema.registry.basic.auth.user.info]": schema-registry:schema-registry-secret
