spring:
  kafka:
    bootstrap-servers: "kafka1.example.com:9092,kafka2.example.com:9092,kafka3.example.com:9092"
    properties:
      "[schema.registry.url]": "http://schema-registry1.example.com:8081,http://schema-registry2.example.com:8081"
      "[replication.factor]": 3
    streams:
      application-id: clickstream-click-event-per-period-app
      client-id: clickstream-click-event-per-period-client
      properties:
        "[commit.interval.ms]": 0
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
    consumer:
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      properties:
        "[metadata.max.age.ms]": 60000

logging:
  level:
    root: info
    org.apache.kafka: info

app:
  topics:
    event:
      topic: clickstream_events
    click-event-per-period:
      topic: clickstream_click_event_per_period
