spring:
  kafka:
    bootstrap-servers: "kafka1.example.com:9092,kafka2.example.com:9092,kafka3.example.com:9092"
    properties:
      "[schema.registry.url]": "http://schema-registry1.example.com:8081,http://schema-registry2.example.com:8081"
      "[replication.factor]": 1
    streams:
      # application-id: clickstream-streams-app
      # client-id: clickstream-streams-client
      properties:
        "[commit.interval.ms]": 0
    producer:
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
    consumer:
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      properties:
        "[metadata.max.age.ms]": 60000

logging:
  level:
    root: info
    org.apache.kafka: info

app:
  topology:
    user-click-event:
      enabled: false
      application-id: user-click-event-app
      client-id: user-click-event-client
      store-name: user-click-event-global-store
    user-click-event-window:
      enabled: false
      application-id: user-click-event-window-app
      client-id: user-click-event-window-client
      store-name: user-click-event-window-store
    click-event-window:
      enabled: false
      application-id: click-event-window-app
      client-id: click-event-window-client
    page-click-event-window:
      enabled: false
      application-id: page-click-event-window-app
      client-id: page-click-event-window-client

  topics:
    create: true
    clickstream:
      topic: clickstream
      partition: 3
      replication-factor: 1
    clickstream-user:
      topic: clickstream_users
      partition: 3
      replication-factor: 1
    clickstream-code:
      topic: clickstream_codes
      partition: 3
      replication-factor: 1
    user-click-event:
      topic: clickstream_user_click_events
      partition: 3
      replication-factor: 1
    user-click-event-window:
      topic: clickstream_user_click_event_window
      partition: 3
      replication-factor: 1
    click-event-window:
      topic: clickstream_click_event_window
      partition: 3
      replication-factor: 1
    page-click-event-window:
      topic: clickstream_page_click_event_window
      partition: 3
      replication-factor: 1
